version: '3.8'
services:
  nodeserver: 
    container_name: nodeServer
    environment:
      - NODE_ENV=production
    build: .
    depends_on:
      - db
      - phpmyadmin
    links:
      - db
    ports:
      - "4000:4000"
  db:
    container_name: mysqlForCars
    image: mysql
    environment:
      - MYSQL_DATABASE=project-car
      - MYSQL_ROOT_PASSWORD=bootcamp2021
    ports:
      - '3306:3306'
    expose:
      - '3306'
  phpmyadmin:
    container_name: phpMyAdminForCars
    image: phpmyadmin
    links:
      - db
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "8080:80"